version: 2.1
jobs:
  build_37:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies & compile
          command: |
            python -m venv venv
            . venv/bin/activate
            python -m pip install --upgrade pip
            python -m pip install -r requirements-dev.txt
            sudo apt-get update && sudo apt-get install protobuf-compiler
            python setup.py bdist_wheel
            python -m pip install -e .
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m unittest test_pycld3.py

workflows:
  version: 2.1
  test:
    jobs:
      - build_37

